// A realistic SaaS indemnity (Sections 10-11) for the demo. It exercises the
// harder logic: an IP-infringement indemnity with combination/compliance
// carve-outs, a separate limitation-of-liability cap, a mutual consequential-
// damages waiver, and Section 11.3 exceptions that carve indemnification (and
// other categories) OUT of those limits. Section 10.4 adds a minimum
// license-efforts period and a wind-down period; Section 11.3 conditions the
// security carve-out on a failure to adhere to agreed Security Requirements and
// makes re-performance the sole remedy for Professional Services.
export const SAMPLE_CLAUSE = `10. INDEMNIFICATION.

10.1 Indemnification. SaaS Provider will defend, indemnify and hold Client and its successors, parents, subsidiaries, Affiliates, officers, directors, employees, users, and attorneys harmless from and against any and all losses, damages, costs, judgments, liabilities, and expenses (including reasonable attorneys' fees, court costs, and disbursements and costs of investigation, litigation, settlement, judgment, interest, fines and penalties) (collectively, "Losses") arising out of or relating to: (i) any Security Event, (ii) any failure by SaaS Provider to comply with Section 8 (Confidentiality and Data Security), including any Security Requirement; or (iii) any third party claims, demands, or proceedings (a "Claim") asserting that the Application Platform, Services, or the use thereof (as permitted under this Agreement) infringes or misappropriates any third party's Intellectual Property Rights.

10.2 Procedure. Client will give SaaS Provider prompt written notice of all Claims for which indemnity is sought hereunder and will provide SaaS Provider with: (a) all related documentation in Client's possession or control relating to such Claims; and (b) reasonable assistance to SaaS Provider in the defense of such Claims. SaaS Provider will control, at SaaS Provider's sole cost and expense, the defense or settlement of all such Claims and will keep Client apprised of the status of all such Claims. Client will have the right, but not the obligation, to participate in the defense of all such Claims with counsel of Client's choice at Client's sole cost and expense. If any settlement requires any action or admission by Client, then the settlement will require Client's prior written consent. Failure by Client to provide prompt notice of a claim or to provide such control, authority, information or assistance will not relieve SaaS Provider of its obligations under this section, except to the extent that SaaS Provider is materially prejudiced by such failure.

10.3 Limitations. SaaS Provider will not have any liability or indemnification obligations to Client under Section 10.1(a)(iii) of this Agreement to the extent that any Losses arise directly as a result of: (a) use of a Application Platform or Services by Client or any third party in combination with equipment, materials, products or software not authorized by SaaS Provider where the Application Platform or Services alone would not be infringing; or (b) compliance with designs, plans, or instructions provided to SaaS Provider by Client.

10.4 License, Replacement or Refund. If the Application Platform or Services becomes the subject of a Claim as set forth in Section 10.1(a)(iii) above or if SaaS Provider believes that the Application Platform or Services is likely to become the subject of a Claim, SaaS Provider may, at its sole discretion and expense: (i) use commercially reasonable efforts for a period of no less than sixty (60) days to obtain a license from such third party for the benefit of Client; (ii) replace or modify the Application Platform or Services ("Replacement") so it is no longer the subject of a Claim so long as such Replacement performs substantially the same functions as the Application Platform or Services at issue; or (iii) only if neither of the foregoing is commercially feasible, terminate this Agreement upon no less than ninety (90) days' prior written notice, during which wind-down period SaaS Provider will continue to provide the Services in accordance with this Agreement, and refund all Charges for Implementation Services and any pre-paid SaaS Charges or Professional Services Charges (as applicable).

11. LIMITATION OF LIABILITY.

11.1 EXCEPT AS OTHERWISE PROVIDED IN SECTION 11.3, IN NO EVENT WILL EITHER PARTY'S TOTAL AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THIS AGREEMENT (INCLUDING, BUT NOT LIMITED TO, CLAIMS FOR NEGLIGENCE, STRICT LIABILITY, BREACH OF CONTRACT, MISREPRESENTATION, INFRINGEMENT OR OTHER CONTRACT OR TORT CLAIMS) EXCEED THE TOTAL CHARGES PAID BY CLIENT TO SAAS PROVIDER DURING THE MOST RECENT 12 MONTH PERIOD PRIOR TO THE LAST EVENT GIVING RISE TO LIABILITY.

11.2 EXCEPT AS OTHERWISE PROVIDED IN SECTION 11.3, IN NO EVENT WILL EITHER PARTY BE LIABLE FOR INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF THIS AGREEMENT EVEN IF INFORMED OF THE POSSIBILITY THEREOF IN ADVANCE.

11.3 THE PARTIES EACH ACKNOWLEDGE AND AGREE THAT THE LIMITATIONS OF LIABILITY SET FORTH IN THIS SECTION 11 (LIMITATION OF LIABILITY) WILL NOT APPLY TO ANY LOSSES AS THE RESULT OF: (A) A SECURITY EVENT OR SAAS PROVIDER'S FAILURE TO COMPLY WITH SECTION 8 (CONFIDENTIALITY AND DATA SECURITY), INCLUDING ANY SECURITY REQUIREMENTS, BUT ONLY TO THE EXTENT SUCH LOSSES ARISE AS A DIRECT RESULT OF SAAS PROVIDER'S FAILURE TO ADHERE TO THE SECURITY REQUIREMENTS EXPRESSLY AGREED BY THE PARTIES; (B) INDEMNIFICATION OBLIGATIONS HEREUNDER; (C) A WILLFUL REFUSAL BY SAAS PROVIDER TO PROVIDE TERMINATION ASSISTANCE SERVICES AS REQUIRED HEREUNDER; (D) FRAUD, WILLFUL MISCONDUCT OR GROSS NEGLIGENCE; OR (E) SERVICE LEVEL CREDITS. NOTWITHSTANDING THE FOREGOING, WITH RESPECT TO ANY PROFESSIONAL SERVICES, CLIENT'S SOLE AND EXCLUSIVE REMEDY, AND SAAS PROVIDER'S ENTIRE LIABILITY, WILL BE RE-PERFORMANCE OF THE DEFICIENT PROFESSIONAL SERVICES.

11.4 Except as otherwise expressly provided herein, all rights and remedies of the Parties are separate and cumulative. The waiver or failure of either Party to exercise in any respect any right or remedy provided herein will not be deemed a waiver of any further right or remedy hereunder.`;
